version: "3.8"

services: 
    redis:
        image: redis:6.0.9-alpine
        container_name: api_redis
        ports:
          - "6379:6379"
        restart: always
        networks:
          - web_api

    postgesql:
        image: postgres:12-alpine
        container_name: api_postgesql
        ports:
        - "5432:5432"
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=auth_db
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        networks:
          - web_api

    prometheus:
        container_name: prometheus_container
        image: prom/prometheus
        restart: always
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
          - ./config/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--storage.tsdb.retention=20d'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
          - '9090:9090'
        networks:
          - web_api

    node_exporter:
        container_name: node_exporter_container
        restart: always
        image: prom/node-exporter
        ports:
          - '9101:9100'
        networks:
          - web_api

    grafana:
        container_name: grafana_container
        restart: always
        image: grafana/grafana
        ports:
          - '3001:3000'
        networks:
          - web_api

    jaeger:
        container_name: jaeger_container
        restart: always
        image: jaegertracing/all-in-one:1.21
        environment:
          - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
          - 5775:5775/udp
          - 6831:6831/udp
          - 6832:6832/udp
          - 5778:5778
          - 16686:16686
          - 14268:14268
          - 14250:14250
          - 9411:9411
        networks:
          - web_api

networks:
    web_api:
        driver: bridge