server:
  Name: TwitterClone
  Description: Simple Prototype for Twitter
  Port: :5000
  PprofPort: :5555
  Mode: Production
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  RateLimit: true
  RateLimitPerSec: 20
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info
  Filename: assets/access.log
  FileMaxSize: 10
  FileMaxAge: 30
  FileMaxBackups: 5
  FileIsCompress: false

postgres:
  PostgresqlHost: postgesql
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: redis:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 86400

metrics:
  url: 0.0.0.0:7070
  service: api

file:
  FilePath: assets/images

jaeger:
  Host: localhost:6831
  ServiceName: TwitterClone
  LogSpans: true